[package]
name = "hbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
crc = "3.0.0"
enum-primitive-derive = "0.2.2"
num-traits = "0.2.15"
serde = "1.0.139"
serde-value = "0.7.0"
