// Generated by gir (https://github.com/gtk-rs/gir @ 74b6e47217b7)
// from /usr/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "FlatpakBundleRef", sizeof(FlatpakBundleRef), alignof(FlatpakBundleRef));
    printf("%s;%zu;%zu\n", "FlatpakBundleRefClass", sizeof(FlatpakBundleRefClass), alignof(FlatpakBundleRefClass));
    printf("%s;%zu;%zu\n", "FlatpakError", sizeof(FlatpakError), alignof(FlatpakError));
    printf("%s;%zu;%zu\n", "FlatpakInstallFlags", sizeof(FlatpakInstallFlags), alignof(FlatpakInstallFlags));
    printf("%s;%zu;%zu\n", "FlatpakInstallation", sizeof(FlatpakInstallation), alignof(FlatpakInstallation));
    printf("%s;%zu;%zu\n", "FlatpakInstallationClass", sizeof(FlatpakInstallationClass), alignof(FlatpakInstallationClass));
    printf("%s;%zu;%zu\n", "FlatpakInstalledRef", sizeof(FlatpakInstalledRef), alignof(FlatpakInstalledRef));
    printf("%s;%zu;%zu\n", "FlatpakInstalledRefClass", sizeof(FlatpakInstalledRefClass), alignof(FlatpakInstalledRefClass));
    printf("%s;%zu;%zu\n", "FlatpakInstance", sizeof(FlatpakInstance), alignof(FlatpakInstance));
    printf("%s;%zu;%zu\n", "FlatpakInstanceClass", sizeof(FlatpakInstanceClass), alignof(FlatpakInstanceClass));
    printf("%s;%zu;%zu\n", "FlatpakLaunchFlags", sizeof(FlatpakLaunchFlags), alignof(FlatpakLaunchFlags));
    printf("%s;%zu;%zu\n", "FlatpakPortalError", sizeof(FlatpakPortalError), alignof(FlatpakPortalError));
    printf("%s;%zu;%zu\n", "FlatpakQueryFlags", sizeof(FlatpakQueryFlags), alignof(FlatpakQueryFlags));
    printf("%s;%zu;%zu\n", "FlatpakRef", sizeof(FlatpakRef), alignof(FlatpakRef));
    printf("%s;%zu;%zu\n", "FlatpakRefClass", sizeof(FlatpakRefClass), alignof(FlatpakRefClass));
    printf("%s;%zu;%zu\n", "FlatpakRefKind", sizeof(FlatpakRefKind), alignof(FlatpakRefKind));
    printf("%s;%zu;%zu\n", "FlatpakRelatedRef", sizeof(FlatpakRelatedRef), alignof(FlatpakRelatedRef));
    printf("%s;%zu;%zu\n", "FlatpakRelatedRefClass", sizeof(FlatpakRelatedRefClass), alignof(FlatpakRelatedRefClass));
    printf("%s;%zu;%zu\n", "FlatpakRemote", sizeof(FlatpakRemote), alignof(FlatpakRemote));
    printf("%s;%zu;%zu\n", "FlatpakRemoteClass", sizeof(FlatpakRemoteClass), alignof(FlatpakRemoteClass));
    printf("%s;%zu;%zu\n", "FlatpakRemoteRef", sizeof(FlatpakRemoteRef), alignof(FlatpakRemoteRef));
    printf("%s;%zu;%zu\n", "FlatpakRemoteRefClass", sizeof(FlatpakRemoteRefClass), alignof(FlatpakRemoteRefClass));
    printf("%s;%zu;%zu\n", "FlatpakRemoteType", sizeof(FlatpakRemoteType), alignof(FlatpakRemoteType));
    printf("%s;%zu;%zu\n", "FlatpakStorageType", sizeof(FlatpakStorageType), alignof(FlatpakStorageType));
    printf("%s;%zu;%zu\n", "FlatpakTransaction", sizeof(FlatpakTransaction), alignof(FlatpakTransaction));
    printf("%s;%zu;%zu\n", "FlatpakTransactionClass", sizeof(FlatpakTransactionClass), alignof(FlatpakTransactionClass));
    printf("%s;%zu;%zu\n", "FlatpakTransactionErrorDetails", sizeof(FlatpakTransactionErrorDetails), alignof(FlatpakTransactionErrorDetails));
    printf("%s;%zu;%zu\n", "FlatpakTransactionOperationClass", sizeof(FlatpakTransactionOperationClass), alignof(FlatpakTransactionOperationClass));
    printf("%s;%zu;%zu\n", "FlatpakTransactionOperationType", sizeof(FlatpakTransactionOperationType), alignof(FlatpakTransactionOperationType));
    printf("%s;%zu;%zu\n", "FlatpakTransactionProgressClass", sizeof(FlatpakTransactionProgressClass), alignof(FlatpakTransactionProgressClass));
    printf("%s;%zu;%zu\n", "FlatpakTransactionRemoteReason", sizeof(FlatpakTransactionRemoteReason), alignof(FlatpakTransactionRemoteReason));
    printf("%s;%zu;%zu\n", "FlatpakTransactionResult", sizeof(FlatpakTransactionResult), alignof(FlatpakTransactionResult));
    printf("%s;%zu;%zu\n", "FlatpakUninstallFlags", sizeof(FlatpakUninstallFlags), alignof(FlatpakUninstallFlags));
    printf("%s;%zu;%zu\n", "FlatpakUpdateFlags", sizeof(FlatpakUpdateFlags), alignof(FlatpakUpdateFlags));
    return 0;
}
